treewide: disable programs.nix-index.enable option by default
nix-community/nix-index-database pull request #132
Opened 2024-12-12 17:45 UTC by trueNAHO

This patchset does some cleanup and disables the `programs.nix-index.enable` option by default for the following reason:

> ```
> treewide: disable programs.nix-index.enable option by default
>
> Disable the programs.nix-index.enable option by default to align with
> Nix conventions and streamline configuration sharing.
>
> This avoids needing to remember to disable this module across all
> configurations and avoids highly discouraged conditional imports that
> often lead to infinite recursions [1].
>
> [...]
>
> [1]: https://discourse.nixos.org/t/conditional-module-imports/34863/2
> ```

---

The `programs.nix-index.enable` option was first introduced in commit 75e347f5b4ac ("Allow command-not-found integration with home-manager.") and set to `true`:

https://github.com/nix-community/nix-index-database/blob/75e347f5b4ac8029dafdcdb38b589d42f5ba1553/home-manager-module.nix#L6

To this day, `programs.nix-index.enable` is still set to `true`:

https://github.com/nix-community/nix-index-database/blob/f1e477a7dd11e27e7f98b646349cd66bbabf2fb8/nix/shared.nix#L6

---

```
NAHO (5):
  tests: remove default option declaration
  readme: remove trailing whitespaces
  treewide: disable programs.nix-index.enable option by default
  readme: improve programs.nix-index-database.comma.enable description
  readme: subjectively improve examples

 README.md      | 88 ++++++++++++++++++++++++++++++++------------------
 nix/shared.nix |  2 --
 tests.nix      |  6 ++--
 3 files changed, 60 insertions(+), 36 deletions(-)
```

2024-12-12 17:55 UTC, r-vdp commented
Should we maybe start by printing a warning if the option is set to true by this module, to give people the chance to update their configs?

2024-12-12 18:03 UTC, trueNAHO commented
> Should we maybe start by printing a warning if the option is set to true by this module, to give people the chance to update their configs?

What about doing the opposite? If `programs.nix-index.enable == false`, then we emit a warning to inform users that this module may have been unbeknownst disabled. This warning should be removed after some time, like after the release of `nixos-25.12`.

2024-12-12 22:45 UTC, r-vdp commented
> > Should we maybe start by printing a warning if the option is set to true by this module, to give people the chance to update their configs?
> 
> What about doing the opposite? If `programs.nix-index.enable == false`, then we emit a warning to inform users that this module may have been unbeknownst disabled. This warning should be removed after some time, like after the release of `nixos-25.12`.
> 

But that warning would be hard to avoid in case you actually conditionally enable the module. I think it should be possible to not have any warnings to avoid warning fatigue.

2024-12-13 13:55 UTC, trueNAHO commented
# Changelog

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2024-12-13 14:01 UTC, trueNAHO commented
# Changelog

## v2:

- Rename commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` to `shared: add programs.nix-index.acknowledgeBreakingChange option.`

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2024-12-23 09:05 UTC, Mic92 commented
@r-vdp can you have a look again?

2024-12-23 22:58 UTC, r-vdp commented
I'll try to have a look at it tomorrow.

I would prefer to move the second commit to another PR, because it's not related to the functional change here and I don't feel like arguing about stylistic changes.

I don't love the idea of the extra option to acknowledge the change, I'd like to avoid it if possible, but if there's no better way, then we leave it.
I wonder if we cannot just assign `lib.warn "..." true` as the option default and have people assign true or false explicitly, instead of introducing yet another option. But I'm not sure if the module system is sufficiently non-strict to avoid forcing values assigned at lower priority than the one that will end up used.

2024-12-24 14:53 UTC, trueNAHO commented
> I would prefer to move the second commit to another PR, because it's not related to the functional change here and I don't feel like arguing about stylistic changes.

The

```
readme: subjectively improve examples
tests: remove default option declaration
```

commits are included in this patchset to avoid merge conflicts with the

```
treewide: disable programs.nix-index.enable option by default
shared: add programs.nix-index.acknowledgeBreakingChange option
```

commits, while the

```
readme: remove trailing whitespaces
```

commit is included in this patchset for simplicity reasons.

> I don't love the idea of the extra option to acknowledge the change, I'd like to avoid it if possible, but if there's no better way, then we leave it. I wonder if we cannot just assign `lib.warn "..." true` as the option default and have people assign true or false explicitly, instead of introducing yet another option. But I'm not sure if the module system is sufficiently non-strict to avoid forcing values assigned at lower priority than the one that will end up used.

The following end-user module triggers the warning when `config.nix-index.enable == false`, if we declare `config.programs.nix-index.enable` to `lib.mkDefault (lib.warn "..." false)`:

```nix
{
  config,
  inputs,
  lib,
  ...
}: {
  imports = [inputs.nix-index-database.hmModules.nix-index];
  options.nix-index.enable = lib.mkEnableOption "nix-index";

  config = lib.mkIf config.nix-index.enable {
    programs = {
      nix-index-database.comma.enable = true;
      nix-index.enable = true;
    };
  };
}
```

In that case, end-users have to use the following potentially undesired workaround:

```patch
11,15c11,13
<   config = lib.mkIf config.nix-index.enable {
<     programs = {
<       nix-index-database.comma.enable = true;
<       nix-index.enable = true;
<     };
---
>   config.programs = {
>     nix-index-database.comma.enable = config.nix-index.enable;
>     nix-index.enable = config.nix-index.enable;
```

If we provide an explicit breaking change option, end-users get a proper warning
once this option is deprecated:

```nix
{
  config,
  inputs,
  lib,
  ...
}: {
  imports = [inputs.nix-index-database.hmModules.nix-index];
  options.nix-index.enable = lib.mkEnableOption "nix-index";

  config = lib.mkMerge [
    {
      # This will trigger a proper warning once this upstream option is
      # deprecated with lib.mkRemovedOptionModule.
      programs.nix-index.acknowledgeBreakingChange = true;
    }

    (
      lib.mkIf config.nix-index.enable {
        programs = {
          nix-index-database.comma.enable = true;
          nix-index.enable = true;
        };
      }
    )
  ];
}
```

Otherwise, end-users have to use the workaround and will never be notified when the workaround is no longer necessary.

2025-01-14 19:26 UTC, trueNAHO commented
# Changelog

## v3: https://github.com/nix-community/nix-index-database/commit/8f6bf3e292fc280e6e6037c61a851b812e9f747e

- Rebase on top of commit commit 271e5bd7c57e ("update generated.nix to release 2025-01-12-031855")

## v2: https://github.com/nix-community/nix-index-database/commit/928ab2e5fa322ed899ebe5679f2335a2c91789f2

- Rename commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` to `shared: add programs.nix-index.acknowledgeBreakingChange option`

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2025-01-25 23:52 UTC, trueNAHO commented
Friendly ping: @r-vdp

2025-02-08 21:33 UTC, trueNAHO commented
# Changelog

## v4: https://github.com/nix-community/nix-index-database/commit/e35a2c27f8ebf0f4bb5e9bd46e394c2e9c56bd84

- Rebase on top of commit 46a8f5fc9552b776bfc5c5c96ea3bede33f68f52 ("update generated.nix to release 2025-02-02-030235")

## v3: https://github.com/nix-community/nix-index-database/commit/8f6bf3e292fc280e6e6037c61a851b812e9f747e

- Rebase on top of commit 271e5bd7c57e ("update generated.nix to release 2025-01-12-031855")

## v2: https://github.com/nix-community/nix-index-database/commit/928ab2e5fa322ed899ebe5679f2335a2c91789f2

- Rename commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` to `shared: add programs.nix-index.acknowledgeBreakingChange option`

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2025-02-09 05:10 UTC, Mic92 commented on nix/shared.nix
> +      nix-index.acknowledgeBreakingChange = lib.mkOption {
Do we even need this option? Can we not just not have not a default set?

2025-02-09 16:18 UTC, trueNAHO commented on nix/shared.nix
> +      nix-index.acknowledgeBreakingChange = lib.mkOption {
This option was introduced in commit https://github.com/nix-community/nix-index-database/pull/132/commits/e35a2c27f8ebf0f4bb5e9bd46e394c2e9c56bd84 to address the following concern:

> Should we maybe start by printing a warning if the option is set to true by this module, to give people the chance to update their configs?
>
> -- https://github.com/nix-community/nix-index-database/pull/132#issuecomment-2539645646

However, I am fine with reverting this commit.

2025-02-27 09:42 UTC, trueNAHO commented
# Changelog

## v5: https://github.com/nix-community/nix-index-database/commit/33b2e6236329f710dcaaff5ff73a099c6bd87c70

- Rebase on top of commit 465792533d03 ("update generated.nix to release 2025-02-23-031515")

## v4: https://github.com/nix-community/nix-index-database/commit/e35a2c27f8ebf0f4bb5e9bd46e394c2e9c56bd84

- Rebase on top of commit 46a8f5fc9552b776bfc5c5c96ea3bede33f68f52 ("update generated.nix to release 2025-02-02-030235")

## v3: https://github.com/nix-community/nix-index-database/commit/8f6bf3e292fc280e6e6037c61a851b812e9f747e

- Rebase on top of commit 271e5bd7c57e ("update generated.nix to release 2025-01-12-031855")

## v2: https://github.com/nix-community/nix-index-database/commit/928ab2e5fa322ed899ebe5679f2335a2c91789f2

- Rename commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` to `shared: add programs.nix-index.acknowledgeBreakingChange option`

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2025-04-19 14:02 UTC, trueNAHO commented
# Changelog

## v6: https://github.com/nix-community/nix-index-database/commit/2072ea44c48c9f7d2d56a10922eea9a0d55918b6

- Rebase on top of commit 4fc9ea78c962 ("update generated.nix to release 2025-04-13-041853")

## v5: https://github.com/nix-community/nix-index-database/commit/33b2e6236329f710dcaaff5ff73a099c6bd87c70

- Rebase on top of commit 465792533d03 ("update generated.nix to release 2025-02-23-031515")

## v4: https://github.com/nix-community/nix-index-database/commit/e35a2c27f8ebf0f4bb5e9bd46e394c2e9c56bd84

- Rebase on top of commit 46a8f5fc9552 ("update generated.nix to release 2025-02-02-030235")

## v3: https://github.com/nix-community/nix-index-database/commit/8f6bf3e292fc280e6e6037c61a851b812e9f747e

- Rebase on top of commit 271e5bd7c57e ("update generated.nix to release 2025-01-12-031855")

## v2: https://github.com/nix-community/nix-index-database/commit/928ab2e5fa322ed899ebe5679f2335a2c91789f2

- Rename commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` to `shared: add programs.nix-index.acknowledgeBreakingChange option`

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2025-04-20 17:36 UTC, r-vdp commented
I agree with the idea behind this PR, but I don't necessarily agree with all of the other changes that you made that have nothing to do with this enable option. I gave you the same feedback before.

So, as before, I'd suggest that you remove those changes from this PR.
Feel free to open a new one for those changes and then we can discuss them there.

2025-04-30 09:49 UTC, trueNAHO commented
# Changelog

## v7: https://github.com/nix-community/nix-index-database/commit/786aecffbf24bd6b8ddc5208c958d5a7236700a8

- Rebase on top of commit 187524713d0d ("update generated.nix to release 2025-04-27-033009")
- Move commit a2d7bdd70e6d ("tests: remove default option declaration") from v6 into https://github.com/nix-community/nix-index-database/pull/145.
- Move and squash commits 27f993059532 ("readme: subjectively improve examples") and 5f9f5d5fc4c2 ("readme: remove trailing whitespaces") from v6 into https://github.com/nix-community/nix-index-database/pull/144. Both commits are squashed into one PR to arguably simplify their reviewing process.

## v6: https://github.com/nix-community/nix-index-database/commit/2072ea44c48c9f7d2d56a10922eea9a0d55918b6

- Rebase on top of commit 4fc9ea78c962 ("update generated.nix to release 2025-04-13-041853")

## v5: https://github.com/nix-community/nix-index-database/commit/33b2e6236329f710dcaaff5ff73a099c6bd87c70

- Rebase on top of commit 465792533d03 ("update generated.nix to release 2025-02-23-031515")

## v4: https://github.com/nix-community/nix-index-database/commit/e35a2c27f8ebf0f4bb5e9bd46e394c2e9c56bd84

- Rebase on top of commit 46a8f5fc9552 ("update generated.nix to release 2025-02-02-030235")

## v3: https://github.com/nix-community/nix-index-database/commit/8f6bf3e292fc280e6e6037c61a851b812e9f747e

- Rebase on top of commit 271e5bd7c57e ("update generated.nix to release 2025-01-12-031855")

## v2: https://github.com/nix-community/nix-index-database/commit/928ab2e5fa322ed899ebe5679f2335a2c91789f2

- Rename commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` to `shared: add programs.nix-index.acknowledgeBreakingChange option`

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2025-04-30 09:54 UTC, trueNAHO commented
> I agree with the idea behind this PR, but I don't necessarily agree with all of the other changes that you made that have nothing to do with this enable option. I gave you the same feedback before.
>
> So, as before, I'd suggest that you remove those changes from this PR. Feel free to open a new one for those changes and then we can discuss them there.

Yes. My bad for not entirely understanding that part at first. I moved all commits except for "treewide: disable programs.nix-index.enable option by default" and "shared: add programs.nix-index.acknowledgeBreakingChange option" into seperate PRs in [v7](https://github.com/nix-community/nix-index-database/pull/132#issuecomment-2841428922).

2025-04-30 13:06 UTC, r-vdp requested changes

2025-04-30 13:06 UTC, r-vdp commented on nix/shared.nix
> +      nix-index.acknowledgeBreakingChange = lib.mkOption {
I think not providing a default at all is indeed better, it will print a clear error that most nix users will easily understand.

Including this option is also a future maintenance issue, we need to decide when to remove it (which will be again a breaking change for people who decided to set it), and it also doesn't make it clear which breaking change you're acknowledging, in case we introduce a new one before we remove this option.

So, I'd remove this option and just not provide a default for the enable option for now.

2025-04-30 13:48 UTC, trueNAHO commented
# Changelog

## v9: https://github.com/nix-community/nix-index-database/commit/fcd8050007dabcc7f17a31407882d90f3c10a9c2

- Drop commit 395c618edf86 ("shared: add programs.nix-index.acknowledgeBreakingChange option")

## v8: https://github.com/nix-community/nix-index-database/commit/395c618edf8610ac32b81435a0db2e3f29ca2dfb

- Revert noisy whitespace changes that were not properly removed when removing commit 5f9f5d5fc4c2 ("readme: remove trailing whitespaces") in v7.

## v7: https://github.com/nix-community/nix-index-database/commit/786aecffbf24bd6b8ddc5208c958d5a7236700a8

- Rebase on top of commit 187524713d0d ("update generated.nix to release 2025-04-27-033009")
- Move commit a2d7bdd70e6d ("tests: remove default option declaration") from v6 into https://github.com/nix-community/nix-index-database/pull/145.
- Move and squash commits 27f993059532 ("readme: subjectively improve examples") and 5f9f5d5fc4c2 ("readme: remove trailing whitespaces") from v6 into https://github.com/nix-community/nix-index-database/pull/144. Both commits are squashed into one PR to arguably simplify their reviewing process.

## v6: https://github.com/nix-community/nix-index-database/commit/2072ea44c48c9f7d2d56a10922eea9a0d55918b6

- Rebase on top of commit 4fc9ea78c962 ("update generated.nix to release 2025-04-13-041853")

## v5: https://github.com/nix-community/nix-index-database/commit/33b2e6236329f710dcaaff5ff73a099c6bd87c70

- Rebase on top of commit 465792533d03 ("update generated.nix to release 2025-02-23-031515")

## v4: https://github.com/nix-community/nix-index-database/commit/e35a2c27f8ebf0f4bb5e9bd46e394c2e9c56bd84

- Rebase on top of commit 46a8f5fc9552 ("update generated.nix to release 2025-02-02-030235")

## v3: https://github.com/nix-community/nix-index-database/commit/8f6bf3e292fc280e6e6037c61a851b812e9f747e

- Rebase on top of commit 271e5bd7c57e ("update generated.nix to release 2025-01-12-031855")

## v2: https://github.com/nix-community/nix-index-database/commit/928ab2e5fa322ed899ebe5679f2335a2c91789f2

- Rename commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` to `shared: add programs.nix-index.acknowledgeBreakingChange option`

## v1: https://github.com/nix-community/nix-index-database/commit/fd1dc4242b789bd6e22309c73a97c4119819eae7

- Add commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option`, allowing end-users to explicitly acknowledge and disable the breaking change warning
- Add more changes to commit `readme: subjectively improve examples`
- Reorder commits such that commit `shared: add config.programs.nix-index.acknowledgeBreakingChange option` and `treewide: disable programs.nix-index.enable option by default` are the last two commits
- Add `Link: https://github.com/nix-community/nix-index-database/pull/132` tag to every commit

## v0: https://github.com/nix-community/nix-index-database/commit/4b18f07e68b1658d07d89176c1a5f315c656d300

2025-04-30 13:49 UTC, trueNAHO commented on nix/shared.nix
> +      nix-index.acknowledgeBreakingChange = lib.mkOption {
Alright. I dropped commit 395c618edf86 ("shared: add programs.nix-index.acknowledgeBreakingChange option") in [v9](https://github.com/nix-community/nix-index-database/pull/132#issuecomment-2842053846), if that is what you meant.

2025-04-30 16:08 UTC, r-vdp approved these changes

2025-04-30 16:09 UTC, r-vdp commented
Thanks!

2025-04-30 16:09 UTC, merged